import { writable } from 'svelte/store'

export const code = writable('vperm2f128 ymm0, ymm0, ymm0, 0x01')

export const registers = writable([
  { name: 'YMM0', size: 8, values: [0, 1, 2, 3, 4, 5, 6, 7] },
  { name: 'YMM1', size: 8, values: [7, 6, 5, 4, 3, 2, 1, 0] },
])

export const history = writable([])

export const register_config = [
  // XMM
  { name: 'XMM0', stroke: 'green', fill: 'purple' },
  { name: 'XMM1', stroke: 'green', fill: 'pink' },
  { name: 'XMM2', stroke: 'green', fill: 'violet' },
  { name: 'XMM3', stroke: 'green', fill: 'indigo' },
  { name: 'XMM4', stroke: 'green', fill: 'orange' },
  { name: 'XMM5', stroke: 'green', fill: 'gray' },
  { name: 'XMM6', stroke: 'green', fill: 'brown' },
  { name: 'XMM7', stroke: 'green', fill: 'coral' },
  { name: 'XMM8', stroke: 'green', fill: 'lime' },
  { name: 'XMM9', stroke: 'green', fill: 'teal' },
  { name: 'XMM10', stroke: 'green', fill: 'olive' },
  { name: 'XMM11', stroke: 'green', fill: 'navy' },
  { name: 'XMM12', stroke: 'green', fill: 'maroon' },
  { name: 'XMM13', stroke: 'green', fill: 'aqua' },
  { name: 'XMM14', stroke: 'green', fill: 'fuchsia' },
  { name: 'XMM15', stroke: 'green', fill: 'silver' },
  // YMM
  { name: 'YMM0', stroke: 'yellow', fill: 'purple' },
  { name: 'YMM1', stroke: 'yellow', fill: 'pink' },
  { name: 'YMM2', stroke: 'yellow', fill: 'violet' },
  { name: 'YMM3', stroke: 'yellow', fill: 'indigo' },
  { name: 'YMM4', stroke: 'yellow', fill: 'orange' },
  { name: 'YMM5', stroke: 'yellow', fill: 'gray' },
  { name: 'YMM6', stroke: 'yellow', fill: 'brown' },
  { name: 'YMM7', stroke: 'yellow', fill: 'coral' },
  { name: 'YMM8', stroke: 'yellow', fill: 'lime' },
  { name: 'YMM9', stroke: 'yellow', fill: 'teal' },
  { name: 'YMM10', stroke: 'yellow', fill: 'olive' },
  { name: 'YMM11', stroke: 'yellow', fill: 'navy' },
  { name: 'YMM12', stroke: 'yellow', fill: 'maroon' },
  { name: 'YMM13', stroke: 'yellow', fill: 'aqua' },
  { name: 'YMM14', stroke: 'yellow', fill: 'fuchsia' },
  { name: 'YMM15', stroke: 'yellow', fill: 'silver' },
  // ZMM
  { name: 'ZMM0', stroke: 'red', fill: 'purple' },
  { name: 'ZMM1', stroke: 'red', fill: 'pink' },
  { name: 'ZMM2', stroke: 'red', fill: 'violet' },
  { name: 'ZMM3', stroke: 'red', fill: 'indigo' },
  { name: 'ZMM4', stroke: 'red', fill: 'orange' },
  { name: 'ZMM5', stroke: 'red', fill: 'gray' },
  { name: 'ZMM6', stroke: 'red', fill: 'brown' },
  { name: 'ZMM7', stroke: 'red', fill: 'coral' },
  { name: 'ZMM8', stroke: 'red', fill: 'lime' },
  { name: 'ZMM9', stroke: 'red', fill: 'teal' },
  { name: 'ZMM10', stroke: 'red', fill: 'olive' },
  { name: 'ZMM11', stroke: 'red', fill: 'navy' },
  { name: 'ZMM12', stroke: 'red', fill: 'maroon' },
  { name: 'ZMM13', stroke: 'red', fill: 'aqua' },
  { name: 'ZMM14', stroke: 'red', fill: 'fuchsia' },
  { name: 'ZMM15', stroke: 'red', fill: 'silver' },
  { name: 'ZMM16', stroke: 'red', fill: 'gold' },
  { name: 'ZMM17', stroke: 'red', fill: 'darkorange' },
  { name: 'ZMM18', stroke: 'red', fill: 'lightcoral' },
  { name: 'ZMM19', stroke: 'red', fill: 'darkviolet' },
  { name: 'ZMM20', stroke: 'red', fill: 'mediumspringgreen' },
  { name: 'ZMM21', stroke: 'red', fill: 'royalblue' },
  { name: 'ZMM22', stroke: 'red', fill: 'darkcyan' },
  { name: 'ZMM23', stroke: 'red', fill: 'beige' },
  { name: 'ZMM24', stroke: 'red', fill: 'tan' },
  { name: 'ZMM25', stroke: 'red', fill: 'darkkhaki' },
  { name: 'ZMM26', stroke: 'red', fill: 'plum' },
  { name: 'ZMM27', stroke: 'red', fill: 'orchid' },
  { name: 'ZMM28', stroke: 'red', fill: 'lightseagreen' },
  { name: 'ZMM29', stroke: 'red', fill: 'steelblue' },
  { name: 'ZMM30', stroke: 'red', fill: 'mediumvioletred' },
  { name: 'ZMM31', stroke: 'red', fill: 'skyblue' },
  // GPR
  { name: 'RAX', stroke: 'blue', fill: 'purple' },
  { name: 'RBX', stroke: 'blue', fill: 'pink' },
  { name: 'RCX', stroke: 'blue', fill: 'violet' },
  { name: 'RDX', stroke: 'blue', fill: 'indigo' },
  { name: 'RSI', stroke: 'blue', fill: 'orange' },
  { name: 'RDI', stroke: 'blue', fill: 'gray' },
  { name: 'RSP', stroke: 'blue', fill: 'brown' },
  { name: 'RBP', stroke: 'blue', fill: 'coral' },
  { name: 'R8', stroke: 'blue', fill: 'lime' },
  { name: 'R9', stroke: 'blue', fill: 'teal' },
  { name: 'R10', stroke: 'blue', fill: 'olive' },
  { name: 'R11', stroke: 'blue', fill: 'navy' },
  { name: 'R12', stroke: 'blue', fill: 'maroon' },
  { name: 'R13', stroke: 'blue', fill: 'aqua' },
  { name: 'R14', stroke: 'blue', fill: 'fuchsia' },
  { name: 'R15', stroke: 'blue', fill: 'silver' },
  { name: 'RIP', stroke: 'blue', fill: 'gold' },
  { name: 'RFLAGS', stroke: 'blue', fill: 'darkorange' },
  { name: 'EAX', stroke: 'blue', fill: 'lightcoral' },
  { name: 'EBX', stroke: 'blue', fill: 'darkviolet' },
  { name: 'ECX', stroke: 'blue', fill: 'mediumspringgreen' },
  { name: 'EDX', stroke: 'blue', fill: 'royalblue' },
  { name: 'ESI', stroke: 'blue', fill: 'darkcyan' },
  { name: 'EDI', stroke: 'blue', fill: 'beige' },
  { name: 'ESP', stroke: 'blue', fill: 'tan' },
  { name: 'EBP', stroke: 'blue', fill: 'darkkhaki' },
  { name: 'EIP', stroke: 'blue', fill: 'plum' },
  { name: 'EFLAGS', stroke: 'blue', fill: 'orchid' },
  { name: 'AX', stroke: 'blue', fill: 'lightseagreen' },
  { name: 'BX', stroke: 'blue', fill: 'steelblue' },
  { name: 'CX', stroke: 'blue', fill: 'mediumvioletred' },
  { name: 'DX', stroke: 'blue', fill: 'skyblue' },
  { name: 'SI', stroke: 'blue', fill: 'lightpink' },
  { name: 'DI', stroke: 'blue', fill: 'darkseagreen' },
  { name: 'SP', stroke: 'blue', fill: 'darkslateblue' },
  { name: 'BP', stroke: 'blue', fill: 'mediumaquamarine' },
  { name: 'IP', stroke: 'blue', fill: 'mediumorchid' },
  { name: 'FLAGS', stroke: 'blue', fill: 'darkolivegreen' },
  { name: 'CS', stroke: 'blue', fill: 'cadetblue' },
  { name: 'DS', stroke: 'blue', fill: 'magenta' },
  { name: 'SS', stroke: 'blue', fill: 'crimson' },
  { name: 'ES', stroke: 'blue', fill: 'darkturquoise' },
  { name: 'FS', stroke: 'blue', fill: 'slategray' },
  { name: 'GS', stroke: 'blue', fill: 'mediumslateblue' },
  { name: 'AH', stroke: 'blue', fill: 'tomato' },
  { name: 'BH', stroke: 'blue', fill: 'orchid' },
  { name: 'CH', stroke: 'blue', fill: 'palevioletred' },
  { name: 'DH', stroke: 'blue', fill: 'slateblue' },
  { name: 'AL', stroke: 'blue', fill: 'mediumseagreen' },
  { name: 'BL', stroke: 'blue', fill: 'mediumblue' },
  { name: 'CL', stroke: 'blue', fill: 'mediumturquoise' },
  { name: 'DL', stroke: 'blue', fill: 'darkmagenta' },
]
